local COMMON = require "libs.common"
local GUI = require "libs_project.gui.gui"
local SM = require "libs_project.sm"

local Script = COMMON.new_n28s()


function Script:init()
	COMMON.input_acquire()
    COMMON.CONTEXT:register(COMMON.CONTEXT.NAMES.GAME,self)
end

function Script:update(dt) end

function Script:final()
	COMMON.input_release()
    COMMON.CONTEXT:unregister(COMMON.CONTEXT.NAMES.GAME)
end

function Script:on_input(action_id, action)

end

COMMON.N28S.register(Script())