local M = {}

M.SYSTEM_INFO = sys.get_sys_info()
M.PLATFORM = M.SYSTEM_INFO.system_name
M.PLATFORM_IS_WEB = M.PLATFORM == "HTML5"
M.PLATFORM_IS_WINDOWS = M.PLATFORM == "Windows"
M.PLATFORM_IS_LINUX = M.PLATFORM == "Linux"
M.PLATFORM_IS_MACOS = M.PLATFORM == "Darwin"
M.PLATFORM_IS_ANDROID = M.PLATFORM == "Android"
M.PLATFORM_IS_IPHONE = M.PLATFORM == "iPhone OS"

M.PLATFORM_IS_PC = M.PLATFORM_IS_WINDOWS or M.PLATFORM_IS_LINUX or M.PLATFORM_IS_MACOS
M.PLATFORM_IS_MOBILE = M.PLATFORM_IS_ANDROID or M.PLATFORM_IS_IPHONE

M.IS_DEBUG = M.PLATFORM_IS_PC

M.GUI_ORDER = {
    MODAL_1 = 3,
    MODAL_2 = 4,
    MODAL_3 = 5,
    DEBUG = 15,
}

M.GAME_SIZE = {
    WIDTH = 540,
    HEIGHT = 960
}

M.level_view_dy = - 50

return M
